### ISSUE TITLE
cx_Oracle.DatabaseError: ORA-01455: converting column overflows integer datatype

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/oracle-to-postgres#17]
Old error, but just for reference. Migration of two or three tables (all named `waveform_signals`) failed with the following error:

```python
Traceback (most recent call last):
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 1131, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 1082, in _fetchall_impl
    return self.cursor.fetchall()
cx_Oracle.DatabaseError: ORA-01455: converting column overflows integer datatype

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_migration.py", line 173, in <module>
    logged,trialrun=trialrun)
  File "oracle-to-postgres/migrate.py", line 119, in copy_data
    data = source_session.execute(query).fetchall()
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 1137, in fetchall
    self.cursor, self.context)
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 1131, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "oracle-to-postgres/env/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 1082, in _fetchall_impl
    return self.cursor.fetchall()
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-01455: converting column overflows integer datatype (Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by tompollard** [comment]
Fix was to convert the columns in the source table to varchar2 before migration (then convert bask to numerical type in the destination database, if necessary):

```sql
ALTER TABLE <schema>.<table> ADD (temp VARCHAR2(100));
UPDATE <schema>.<table> SET temp = <column>;
ALTER TABLE <schema>.<table> DROP COLUMN <column>;
ALTER TABLE <schema>.<table> RENAME COLUMN temp TO <column>;
```
